### ISSUE TITLE
[FR] Patch with original graphics by default

### ISSUE THREAD

**Issue by vanfanel** [toruzz/SuperMarioLandDX#3]
Hi @toruzz 

This 2.0 version is just incredible, I am sure you know that. 
But the absolute perfection, for me, is how it looks with the original graphics option selected.

Would it be possible to have a patch with those original graphics selected by default without having to enter the menu to select them each time, etc?

Or... Maybe you can just tell me what value I can change on the patched ROM with an hex editor, that will be enough :)

Thanks!! Enjoying this immensely!

**Comment by toruzz** [comment]
Thank you!

You don't have to enter the menu to select them each time, since your options are saved to the cart (or .sav in emulators) and loaded when the game boots. But if for whatever reason you still want to change the default options (which again, would only affect the very first boot), change line 267 in main.asm from:
```
xor a
ld (GraphicsFlag),a
ld (PlayerFlag),a
ld (ModeFlag),a
```
to:
```
ld a,$01
ld (GraphicsFlag),a
xor a
ld (PlayerFlag),a
ld (ModeFlag),a
```

**Comment by vanfanel** [comment]
@toruzz Ok!! I hadn't noticed the option to be saved, just PERFECT!!!
I have no words, really, this hack is so sweet!
